const booksData = [

{"Título": "História e Devoção", "Autor": "Mauricio de Aquino", "Ano": "2011", "posicao": "A1"},
{"Título": "Divina Comunhão - Festa de Todos os Sons", "Autor": "Marco Aurelio Gomes, Neusa Fleury Moraes", "Ano": "2010", "posicao": "A2"},
{"Título": "Um olhar sobre a presença japonesa em Ourinhos", "Autor": "Marco Aurelio Gomes, Neusa Fleury Moraes", "Ano": "2008", "posicao": "A3"},
{"Título": "Memórias do Secúlo XX", "Autor": "Mason Antony", "Ano": "2003", "posicao": "A4"},
{"Título": "Ourinhos - Cidade da Dança", "Autor": "Rafael Lefcadito Álvares, Terezinha de Paula, Vanderley Silva", "Ano": "2012", "posicao": "A5"},
{"Título": "Novas Hístorias de Ouro", "Autor": "Não informado", "Ano": "Não informado", "posicao": "A6"},
{"Título": "Um espaço para lembranças de Ourinhos", "Autor": "Fernanda Saraiva Romera, Rosemary Reginato de Moraes", "Ano": "2004", "posicao": "A7"},
{"Título": "Do Diamante Mineiro aos Canaviais Paulistas", "Autor": "Sandra Regina Gomes", "Ano": "2008", "posicao": "A8"},
{"Título": "Saudades do Século 20", "Autor": "Ruy Castro", "Ano": "1994", "posicao": "A9"},
{"Título": "O Jovem Noel Rosa", "Autor": "Guca Domenico", "Ano": "2003", "posicao": "A10"},
{"Título": "Crônicas Escolhidas", "Autor": "Lima Barreto", "Ano": "Não informado", "posicao": "A11"},
{"Título": "O curioso caso de Benjamin Button", "Autor": "F. Scott Fitzgerald", "Ano": "1922", "posicao": "A12"},
{"Título": "O Pensamento Vivo de Sartre", "Autor": "Não informado", "Ano": "1990", "posicao": "A13"},
{"Título": "O Pensamento vivo de Picasso", "Autor": "Não informado", "Ano": "1985", "posicao": "A14"},
{"Título": "O Pesamento vivo de Nietzsche", "Autor": "Não informado", "Ano": "1991", "posicao": "A15"},
{"Título": "Os grandes humanistas Charlie Chaplin", "Autor": "Pam Brown", "Ano": "1990", "posicao": "A16"},
{"Título": "O poder Psíquico das Pirâmides", "Autor": "Bill Schul & Ed Pettit", "Ano": "1976", "posicao": "A17"},
{"Título": "Crônicas Esocolhidas", "Autor": "Machado de Assis", "Ano": "Não informado", "posicao": "A18"},
{"Título": "Ourinhos - São Paulo", "Autor": "Não informado", "Ano": "1918", "posicao": "A18"},
{"Título": "Ourinhos Memôrias de uma Cidade Paulista", "Autor": "Jefferson Del Rios", "Ano": "1992", "posicao": "A19"},
{"Título": "Memórias Dos Trilhos", "Autor": "Fabiana Lopes da Cunha", "Ano": "2014", "posicao": "A20"},
{"Título": "Globalização, Logística e Transporte Aéreo", "Autor": "Josef Barat", "Ano": "Não informado", "posicao": "A21"},
{"Título": "Os 100 melhores filmes do século 20", "Autor": "Rubens Ewald Filho", "Ano": "2001", "posicao": "A22"},
{"Título": "O Amor me trouxe de Volta", "Autor": "Carol Bowman", "Ano": "2001", "posicao": "A23"},
{"Título": "Correio do Além", "Autor": "Francisco Candido Xavier Espiritos Diversos", "Ano": "1983", "posicao": "A24"},
{"Título": "Marilyn Monroe", "Autor": "Biografia", "Ano": "Não informado", "posicao": "A25"},
{"Título": "Uma história de Ontem", "Autor": "Mônica de Castro", "Ano": "2001", "posicao": "A26"},
{"Título": "Tudo a seu tempo", "Autor": "Elisa Masselli", "Ano": "Não informado", "posicao": "A27"},
{"Título": "Evita Perón", "Autor": "Biografia", "Ano": "Não informado", "posicao": "A28"},
{"Título": "O Grande Gênio Albert Einstein", "Autor": "Fernanda Cury", "Ano": "2003", "posicao": "A29"},
{"Título": "Internet como expressão da indústria cultural", "Autor": "Marcimedes Martins da Silva", "Ano": "2008", "posicao": "A30"},
{"Título": "Dalai Lama", "Autor": "Biografia", "Ano": "Não informado", "posicao": "A31"},
{"Título": "Mahatma Gandhi", "Autor": "Biografia", "Ano": "Não informado", "posicao": "A32"},
{"Título": "A vida e o pensamento de Che Guevara", "Autor": "Morgana Gomes", "Ano": "Não informado", "posicao": "A33"},
{"Título": "Elvis", "Autor": "Biografia", "Ano": "2008", "posicao": "B1"},
{"Título": "Esmeralda", "Autor": "Zibia Gasparetto", "Ano": "2016", "posicao": "B2"},
{"Título": "Comer, Rezar e Amar", "Autor": "Elizabeth Gilbert", "Ano": "2010", "posicao": "B3"},
{"Título": "Jacqueline Kennedy", "Autor": "Biografia", "Ano": "1999", "posicao": "B4"},
{"Título": "Raul Seixas", "Autor": "Biografia", "Ano": "1999", "posicao": "B5"},
{"Título": "Ayrton Senna", "Autor": "Biografia", "Ano": "2006", "posicao": "B6"},
{"Título": "A vida e o pensamento de Charles Chaplin", "Autor": "Morgana Gomes", "Ano": "", "posicao": "B7"},
{"Título": "Ouvindo Estrelas", "Autor": "Marco Mazzola", "Ano": "2007", "posicao": "B8"},
{"Título": "Recordando Ayrton Senna", "Autor": "Alan Henry", "Ano": "", "posicao": "B9"},
{"Título": "Beatles", "Autor": "Revista", "Ano": "2009", "posicao": "B10"},
{"Título": "Raul Seixas", "Autor": "Revista", "Ano": "2004", "posicao": "B11"},
{"Título": "Michael Jackson - Uma História Sem Fim", "Autor": "Antero Leivas", "Ano": "", "posicao": "B12"},
{"Título": "Beatles - A história ilustrada", "Autor": "Biografia", "Ano": "", "posicao": "B13"},
{"Título": "Steve Jobs", "Autor": "Revista", "Ano": "", "posicao": "B14"},
{"Título": "Bob Marley", "Autor": "Fernando Moretti", "Ano": "", "posicao": "B15"},
{"Título": "Caymmi", "Autor": "Biografia", "Ano": "2014", "posicao": "B16"},
{"Título": "The Beatles - A maior banda de todos os tempos", "Autor": "Antero Leivas", "Ano": "2018", "posicao": "B17"},
{"Título": "De frente com a verdade", "Autor": "Mônica de Castro", "Ano": "2010", "posicao": "B18"},
{"Título": "A verdade de cada um", "Autor": "Zibia Gasparetto", "Ano": "2014", "posicao": "B19"},
{"Título": "Fotografia com bom senso", "Autor": "Leonardo Gaunt", "Ano": "1997", "posicao": "B20"},
{"Título": "Quando O Amor Vence O Ódio", "Autor": "Marlene Saes", "Ano": "2013", "posicao": "B21"},
{"Título": "Vencendo o passado", "Autor": "Zibia Gasparetto", "Ano": "2008", "posicao": "B22"},
{"Título": "Ainda sou Eu", "Autor": "Jojo Moyes", "Ano": "2018", "posicao": "B23"},
{"Título": "O morro dos ventos", "Autor": "Vera Lúcia Marinzeck de Carvalho", "Ano": "2018", "posicao": "B24"},
{"Título": "Vida Após a Morte", "Autor": "D.Scott Rogo", "Ano": "1991", "posicao": "B25"},
{"Título": "Força Para Viver", "Autor": "Jamie Buckingham", "Ano": "1983", "posicao": "B26"},
{"Título": "Ah, se eu pudesse voltar no Tempo", "Autor": "Antônio Carlos e Vera Lúcia Marinzeck", "Ano": "2006", "posicao": "B27"},
{"Título": "A perde de Entes Queridos", "Autor": "Zilda Giunchetti Rosin", "Ano": "", "posicao": "B28"},
{"Título": "O Segredo da Libélula", "Autor": "Scott Blum", "Ano": "2009", "posicao": "B29"},
{"Título": "Pôr do Sol no Central Park", "Autor": "Sarah Morgan", "Ano": "2016", "posicao": "B30"},
{"Título": "Ponte das Lembranças", "Autor": "Eliana Machado Coelho", "Ano": "2010", "posicao": "B31"},
{"Título": "Entre Duas Vidas", "Autor": "Francisco Cândido Xavier e Elias Barbosa", "Ano": "", "posicao": "B32"},
{"Título": "O Advogado de Deus", "Autor": "Lucius Zibia Gasparetto", "Ano": "1999", "posicao": "B33"},
{"Título": "O Caso de Reencarnação", "Autor": "Yvonne A.Pereira", "Ano": "2009", "posicao": "B34"},
{"Título": "De Volta à Cabana", "Autor": "C.Baxter Kruger", "Ano": "2011", "posicao": "B35"},
{"Título": "Dois a Dois", "Autor": "Nicholas Sparks", "Ano": "2016", "posicao": "B36"},
{"Título": "Entra a Razão e o Coração", "Autor": "Maria Gertrudes Coelho Maluf", "Ano": "1994", "posicao": "B37"},
{"Título": "Voltas que a vida dá", "Autor": "Zibia M.Gasparetto", "Ano": "", "posicao": "B38"},
{"Título": "Reencontros", "Autor": "Francisco Cândido Xavier", "Ano": "", "posicao": "B39"},
{"Título": "Mundo Pararelo", "Autor": "Neide Maganba", "Ano": "2001", "posicao": "B40"},
{"Título": "Lindos casos de bezerra de Menezes", "Autor": "Ramiro Gama", "Ano": "1983", "posicao": "B41"},
{"Título": "Fenômenos Espíritas no Mundo Animal", "Autor": "Carlos Bernardo Loureiro", "Ano": "1997", "posicao": "B42"},
{"Título": "Almas Gêmeas", "Autor": "Nicholas Sparks", "Ano": "2018", "posicao": "B43"},
{"Título": "Escravo Bernardino", "Autor": "Vera Lúcia Marinzeck de Carvalho", "Ano": "1998", "posicao": "B44"},
{"Título": "A Escolha", "Autor": "Nicholas Sparks", "Ano": "2010", "posicao": "B45"},
{"Título": "A vida é feita de Escolhas", "Autor": "Elisa Masselli", "Ano": "2010", "posicao": "B46"},
{"Título": "Quando é Preciso Partir", "Autor": "Berenice Germano", "Ano": "2011", "posicao": "B47"},
{"Título": "Você Faz o Amanhã", "Autor": "Marcelo Cezar", "Ano": "2005", "posicao": "B48"},
{"Título": "Entre Quatro Paredes", "Autor": "B.A. Paris", "Ano": "2016", "posicao": "B49"},
{"Título": "Auto Escola - Sérgio", "Autor": "Revista", "Ano": "", "posicao": "B50"},
{"Título": "História de Humor", "Autor": "Revista", "Ano": "", "posicao": "B51"},
{"Título": "Cérebro Lado Esquerdo Lado Direito", "Autor": "Charles Phillips", "Ano": "2009", "posicao": "B52"},
{"Título": "52 Maneiras de Melhorar a Memória", "Autor": "", "Ano": "2008", "posicao": "B53"},
{"Título": "Guia de Orientação - Sobre uso de Experiências com réplicas de pirâmides", "Autor": "Revistinha", "Ano": "", "posicao": "B54"},
{"Título": "Guia de Ourinhos", "Autor": "Revista", "Ano": "2011", "posicao": "B55"},
{"Título": "Orientador de Exercícios Físicos e Respiratórios", "Autor": "Revistinha", "Ano": "", "posicao": "B56"},
{"Título": "Vida e Obra - Miguel de Cervantes", "Autor": "Miguel de Cervantes", "Ano": "2002", "posicao": "B57"},
{"Título": "Vida e Obra - Dante Aligbieri", "Autor": "Dante Aligbieri", "Ano": "2002", "posicao": "B58"},
{"Título": "Conheça seu Anjo", "Autor": "Victor Civita", "Ano": "2008", "posicao": "C1"},
{"Título": "Ponto de Encontro", "Autor": "Celso Martins e Deolindo Amorim", "Ano": "", "posicao": "C2"},
{"Título": "Voltas que a Vida Dá", "Autor": "Zibia M. Gasparetto", "Ano": "1987", "posicao": "C3"},
{"Título": "Retornando - A Ciência da Reencarnação", "Autor": "A.C. Bhanktivedanta Swami Prabhupada", "Ano": "1983", "posicao": "C4"},
{"Título": "O que é o Espiritismo", "Autor": "Geraldo Ferreira", "Ano": "", "posicao": "C5"},
{"Título": "O romance de Arina", "Autor": "Valeska Perez Sarti", "Ano": "1998", "posicao": "C6"},
{"Título": "Râja Yoga", "Autor": "Swâmi Vivekânanda", "Ano": "", "posicao": "C7"},
{"Título": "Râja Yoga ou Desenvolvimento Mental", "Autor": "Yogi Ramacharaka", "Ano": "1928", "posicao": "C8"},
{"Título": "Do Calvário ao Infinito", "Autor": "Zilda Gama", "Ano": "1944", "posicao": "C9"},
{"Título": "O Livro dos Mediums", "Autor": "Allan Kardec", "Ano": "1937", "posicao": "C10"},
{"Título": "Libertação", "Autor": "Francisco Cândido Xavier", "Ano": "1949", "posicao": "C11"},
{"Título": "Além do Nascimento e da Morte", "Autor": "A.C. Bhanktivedanta Swami Prabhupada", "Ano": "2014", "posicao": "C12"},
{"Título": "Entre a Terra e o Céu", "Autor": "Francisco Cândido Xavier", "Ano": "1954", "posicao": "C13"},
{"Título": "Orientações Espíritas", "Autor": "Victor Rebelo", "Ano": "", "posicao": "C14"},
{"Título": "Shinsokan", "Autor": "Dr. Masaharu Taniguchi", "Ano": "", "posicao": "C15"},
{"Título": "Kanro no Hoou", "Autor": "Masaharu Taniguchi", "Ano": "", "posicao": "C16"},
{"Título": "Espiritismo passo a passo com Kardec", "Autor": "Christiano Torchi", "Ano": "", "posicao": "C17"},
{"Título": "Fácil Viagem a outros Planetas", "Autor": "A.C. Bhanktivedanta Swami Prabhupada", "Ano": "1975", "posicao": "C18"},
{"Título": "Ensinamentos Dos Mestres Para A Vida Diária", "Autor": "", "Ano": "1953", "posicao": "C19"},
{"Título": "Eles Vivem", "Autor": "Chico Xavier", "Ano": "2018", "posicao": "C20"},
{"Título": "Espiritismo e o Centro Espírita", "Autor": "Allan Kardec", "Ano": "2017", "posicao": "C21"},
{"Título": "Ação e Reação", "Autor": "Francisco Cândido Xavier", "Ano": "1956", "posicao": "C22"},
{"Título": "Homeopatia e Espiritismo", "Autor": "Lauro S.Thiago", "Ano": "1972", "posicao": "C23"},
{"Título": "Almas que Voltam", "Autor": "Fernado do Ó", "Ano": "1947", "posicao": "C24"},
{"Título": "Há 2000 Anos", "Autor": "Francisco Cândido Xavier", "Ano": "", "posicao": "C25"},
{"Título": "O Futuro Decifrado", "Autor": "Ellen G. White", "Ano": "", "posicao": "C26"},
{"Título": "Meu Livro de Espiritismo", "Autor": "Chico Xavier", "Ano": "2017", "posicao": "C27"},
{"Título": "O Evangelho no Lar", "Autor": "Allan Kardec", "Ano": "2014", "posicao": "C28"},
{"Título": "Pais Brilhantes Professores Fascinantes", "Autor": "Augusto Cury", "Ano": "2003", "posicao": "C29"},
{"Título": "Ansiedade - Como Enfrentar o Mau do Século", "Autor": "Augusto Cury", "Ano": "2013", "posicao": "C30"},
{"Título": "Desvendando O Espiritismo", "Autor": "Luis Eduardo de Souza", "Ano": "2014", "posicao": "C31"},
{"Título": "O que é o Espiritismo", "Autor": "Allan Kardec", "Ano": "2009", "posicao": "C32"},
{"Título": "Aprenda a Viver em Paz", "Autor": "Hugh Prather", "Ano": "2005", "posicao": "C33"},
{"Título": "Autocontrole", "Autor": "Augusto Cury", "Ano": "2015", "posicao": "C34"},
{"Título": "52 maneiras de relaxar", "Autor": "revistinha", "Ano": "2008", "posicao": "C35"},
{"Título": "A Arte da Meditação", "Autor": "Daniel Goleman", "Ano": "1998", "posicao": "C36"},
{"Título": "Lidere sua Mente", "Autor": "Augusto Cury", "Ano": "", "posicao": "C37"},
{"Título": "Chico Xavier - Luz e Sabedoria", "Autor": "Biografia", "Ano": "", "posicao": "C38"},
{"Título": "Estudo Sistematizado da Doutrina Espírita - Tomo 1", "Autor": "", "Ano": "2007", "posicao": "C39"},
{"Título": "Estudo Sistematizado da Doutrina Espírita - Tomo 2", "Autor": "", "Ano": "", "posicao": "C40"},
{"Título": "Eles Continuam Entre Nós", "Autor": "Zibia Gasparetto", "Ano": "2008", "posicao": "C41"},
{"Título": "Mensagens de Paz de Chico Xavier", "Autor": "Chico Xavier", "Ano": "2010", "posicao": "C42"},
{"Título": "O Livro dos Espiritos", "Autor": "Allan Kardec", "Ano": "1999", "posicao": "C43"},
{"Título": "Caminhos De Volta", "Autor": "Francisco Cândido Xavier", "Ano": "", "posicao": "C44"},
{"Título": "O Matuto", "Autor": "Zibia Gasparetto", "Ano": "", "posicao": "C45"},
{"Título": "200 Teáticas da Conscienciologia", "Autor": "Waldo Vieira", "Ano": "1997", "posicao": "C46"},
{"Título": "100 Testes da Conscienciologia", "Autor": "Waldo Vieira", "Ano": "1997", "posicao": "C47"},
{"Título": "Pelas Portas Do Coração", "Autor": "Zibia Gasparetto", "Ano": "", "posicao": "C48"},
{"Título": "O caminho Dos Sinais ", "Autor": "Fernando Toledo", "Ano": "2008", "posicao": "C49"},
{"Título": "Adeus Solidão", "Autor": "Francisco Cândido Xavier & Caio Ramacciotti", "Ano": "2010", "posicao": "C50"},
{"Título": "Deficiente Mental - Por que Fui Um?", "Autor": "Vera Lúcia Marinzeck de Carvalho", "Ano": "1998", "posicao": "C51"},
{"Título": "O que é o Espiritismo", "Autor": "Allan Kardec", "Ano": "", "posicao": "C52"},
{"Título": "Sonhos - A Primeira Mediunidade", "Autor": "Márcio de Carvalho", "Ano": "2000", "posicao": "C53"},
{"Título": "Só o Amor é Real", "Autor": "Brian Weiss", "Ano": "1996", "posicao": "C54"},
{"Título": "O Livro Dos Espíritos", "Autor": "Allan Kardec", "Ano": "1974", "posicao": "C55"},
{"Título": "O que é o Espiritismo", "Autor": "Allan Kardec", "Ano": "1974", "posicao": "C56"},
{"Título": "O Céu e o Inferno", "Autor": "Allan Kardec", "Ano": "1991", "posicao": "C57"},
{"Título": "O Livro dos Médiuns", "Autor": "Allan Kardec", "Ano": "1987", "posicao": "C58"},
{"Título": "O Evangelho Segundo O Espiritismo", "Autor": "Allan Kardec", "Ano": "1978", "posicao": "C59"},
{"Título": "Obras Póstumas", "Autor": "Allan Kardec", "Ano": "1993", "posicao": "C60"},
{"Título": "A Gênese", "Autor": "Allan Kardec", "Ano": "1992", "posicao": "C61"},
{"Título": "Minhas Vidas", "Autor": "Shirley MacLaine", "Ano": "1983", "posicao": "C62"},
{"Título": "Você Sempre Ganha", "Autor": "Zibia Gasparetto", "Ano": "2016", "posicao": "C63"},
{"Título": "Tudo Valeu A Pena", "Autor": "Zibia Gasparetto", "Ano": "2004", "posicao": "C64"},
{"Título": "Espiritismo e Ecologia", "Autor": "André Trigueiro", "Ano": "2009", "posicao": "C65"},
{"Título": "Violetas na Janela", "Autor": "Vera Lúcia Marinzeck de Carvalho", "Ano": "1993", "posicao": "C66"},
{"Título": "O tempo - Oportunidade de Evolução", "Autor": "Wanda A. Canutti", "Ano": "2004", "posicao": "C67"},
{"Título": "Tristão Isolda", "Autor": "Helena Gomes", "Ano": "2010", "posicao": "C68"},
{"Título": "Cora Coralina", "Autor": "Darey França Denófrio", "Ano": "2004", "posicao": "C69"},
{"Título": "Nova Reunião - 23 Livros de Poesia", "Autor": "Carlos Drummond de Andrade", "Ano": "2013", "posicao": "C70"},
{"Título": "Força Diária", "Autor": "Revistinha", "Ano": "2000", "posicao": "C71"},
{"Título": "O Segredo", "Autor": "Rhonda Byrne", "Ano": "2006", "posicao": "C72"}

]